movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.watch_now, name='watch_now'),
    path('library/', views.movie_library, name='movie_library'),
    path('custom-filter/', views.custom_filter, name='custom-filter'),
    path('add-item/', views.add_item, name='add_movie'),
    path('edit_movie/<int:id>', views.edit_item, name='edit_movie'),
    path('delete_item/<int:id>', views.delete_item, name='delete_item'),

]

movie_recommender/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls', namespace='movie')),
    path('account/', include('account.urls', namespace='account')),
    path('account/', include('django.contrib.auth.urls')),

]

movie/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Movie(models.Model):
    STATUS_CHOICES = (
        ('Movie', 'Movie'),
        ('Tv-series', 'Tv Series'),
        ('Anime', 'Anime'),
    )
    WATCH_CHOICES = (
        ('Watched', 'Watched'),
        ('To watch', 'To watch'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=False)
    type = models.CharField(max_length=15,
                            choices=STATUS_CHOICES,
                            default='')
    watch = models.CharField(max_length=20,
                             choices=WATCH_CHOICES)
    year = models.IntegerField(null=True, blank=True)
    rating = models.FloatField(max_length=10, null=False)
    review = models.TextField(null=True, blank=True)
    img_url = models.TextField(default='https://betravingknows.com/wp-content/uploads/2017/'
                                       '06/video-movie-placeholder-image-grey.png')
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

movie/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'review',
                  'rating', 'img_url',
                  'watch', 'type',
                  'active')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'review': forms.TextInput(attrs={'class': 'form-control'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                              'style': 'margin-bottom: 10px;'}),
            'rating': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'img_url', 'watch', 'active')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                              'style': 'margin-bottom: 10px;'}),
            'rating': forms.TextInput(attrs={'class': 'form-control'}),
        }

movie/views.py
from django.shortcuts import render, redirect
from .movie_recommender import movie_list_creator, trailer_finder, poster_finder, movie_list, randomizer
from .movie_dialoge_generater import quotes
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import MovieForm, EditForm
import random
from .models import Movie
from django.contrib.auth.decorators import login_required


def watch_now(request):
    quote = random.choice(quotes)
    random_movie = random.choice(movie_list)
    random_movie['poster'] = poster_finder(random_movie)
    random_movie['trailer'] = trailer_finder(random_movie)
    return render(request, 'movie/watch_now.html', {
        'movie': random_movie,
        'quote': quote,
    })


def custom_filter(request):
    quote = random.choice(quotes)
    if request.method == "POST":
        if 'movies' in request.session:
            del request.session['movies']
        request.session['from_year'] = request.POST['from-year']
        request.session['to_year'] = request.POST['to-year']
        try:
            request.session['genre'] = request.POST['genre']
        except:
            request.session['genre'] = ''
        request.session['from_rating'] = request.POST['from-rating']
        request.session['to_rating'] = request.POST['to-rating']
        custom_movie_list = movie_list_creator(request.session['from_year'],
                                               request.session['to_year'],
                                               request.session['genre'],
                                               request.session['from_rating'],
                                               request.session['to_rating'],
                                               )
        request.session['movies'] = custom_movie_list
    try:
        x_movie_list = request.session['movies']
    except KeyError:
        x_movie_list = movie_list
    try:
        start, end = randomizer(request.session['movies'])
    except KeyError:
        start, end = randomizer(movie_list)
    new_list = []
    for movie in x_movie_list[start:end]:
        movie['poster'] = poster_finder(movie)
        movie['trailer'] = trailer_finder(movie)
        new_list.append(movie)
    return render(request, 'movie/custom-filter.html', {'movies': new_list,
                                                        'quote': quote,
                                                        })


@login_required
def add_item(request):  # add new media
    quote = random.choice(quotes)
    user = request.user
    if request.method == "POST":
        path = request.POST.get('path')
        if not path:
            # if the add request is from add item page.
            form = MovieForm(request.POST)
            if form.is_valid():
                new_item = form.save(commit=False)
                new_item.author = user
                new_item.save()
                return redirect('movie:movie_library')
        else:
            # if the request is direct from the watch now or custom filter page.
            title = request.POST['title']
            image_url = request.POST['img_url']
            # year = request.POST['year']
            rating = request.POST['rating']
            new_item = Movie(title=title, img_url=image_url,
                             rating=rating, author=user,
                             watch="To watch")
            new_item.save()
            return redirect(path)
    return render(request, 'movie/add_movie.html',
                  context={'form': MovieForm(),
                           'quote': quote})


@login_required
def movie_library(request):  # movie library
    user = request.user
    quote = random.choice(quotes)
    movies = Movie.objects.filter(author=user, active=True)
    # paginator = Paginator(movies, 12)
    # page = request.GET.get('page')
    # try:
    #     movies = paginator.page(page)
    # except PageNotAnInteger:
    #     movies = paginator.page(1)
    # except EmptyPage:
    #     movies = paginator.page(paginator.num_pages)
    return render(request, 'movie/library/list.html', {'movies': movies,
                                                       'quote': quote,
                                                       # 'page': page,
                                                       'total': len(movies),
                                                       })


@login_required
def edit_item(request, id):
    movie = Movie.objects.get(pk=id)
    data = {'title': movie.title,
            'img_url': movie.img_url,
            'watch': movie.watch,
            'active': movie.active}
    form = EditForm(initial=data)
    if request.user == movie.author:
        if request.method == "POST":
            form = EditForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                movie.title = cd['title']
                movie.img_url = cd['img_url']
                movie.watch = cd['watch']
                movie.active = cd['active']
                movie.save()
                return redirect('movie:movie_library')
    return render(request, 'movie/edit_movie.html',
                  {'form': form,
                   'id': movie.id})


@login_required
def delete_item(request, id):
    movie = Movie.objects.get(pk=id)
    if request.user == movie.author:
        movie.delete()
        return redirect('movie:movie_library')

templates/movie/add_movie.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add new item{% endblock %}

{% block nav %}
<link rel="stylesheet" href="{% static 'stylesheets/library/custom_style.css' %}">
<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1 class="display-4">Add new item</h1>
		<p class="lead">{{ quote }}</p>
	</div>
</div>

{% endblock %}

{% block content %}
    <div class="container">
<div class="form-group">
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
</div>

{% endblock %}

templates/movie/custom-filter.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Movie Recommender{% endblock %}

{% block nav %}
<link rel="stylesheet" href="{% static 'stylesheets/library/custom_style.css' %}">
<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1 class="display-4">Custom movie recommender</h1>
{#		<p class="lead">{{ quote }}</p>#}
	</div>
</div>
<div class="container">
    <form action="{% url 'movie:custom-filter' %}" method="POST">
	{% csrf_token %}
	<div class="row">
		<div class="col">
			Release year
			<div class="row">
				<div class="col">
					<input type="text" name="from-year" class="form-control form-control-sm" placeholder="From e.g 1996">
				</div>
				<div class="col"><input name="to-year" type="text" class="form-control form-control-sm" placeholder="To e.g 2018">
				</div>
			</div>
		</div>

		<div class="col">
			Genre
			<select class="form-control form-control-sm" name="genre">
				<option value="" disabled selected>Genre</option>
				<option value="sci_fi" >Sci-Fi</option>
				<option value="thriller" >Thriller</option>
				<option value="action">Action</option>
				<option value="adventure">Adventure</option>
				<option value="animation" >Animation</option>
				<option value="biography" >Biography</option>
				<option value="comedy" >Comedy</option>
				<option value="crime" >Crime</option>
				<option value="documentary" >Documentary</option>
				<option value="drama" >Drama</option>
				<option value="fantasy" >Fantasy</option>
				<option value="history" >History</option>
				<option value="horror" >Horror</option>
				<option value="mystery" >Mystery</option>

			</select>
		</div>
		<div class="col">
			Rating
			<div class="row">
				<div class="col">
					<input type="text" name="from-rating" class="form-control form-control-sm" placeholder="From rating e.g. 7">
				</div>
				<div class="col">
					<input name="to-rating" type="text" class="form-control form-control-sm" placeholder="To rating e.g. 9">
				</div>
			</div>
		</div>
	</div>
	<br><p align="center"><button style="background-color: #ea3a60; color: whitesmoke; border-radius: 4px;
	 border-color: #ea3a60;" btn btn-primary type="submit">Filter</button></p>
</form>
    </div>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
	integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<style>
	img {
		-webkit-user-drag: none;
		-moz-user-drag: none;
		-o-user-drag: none;
		user-drag: none;
	}

	img {
		pointer-events: none;
	}

	.movie_card {
		padding: 0 !important;
		width: 15rem;
		margin: 14px;
		border-radius: 10px;
		box-shadow: 0 3px 4px 0 rgba(0, 0, 0, 0.2), 0 4px 15px 0 rgba(0, 0, 0, 0.19);
	}

	.movie_card img {
		border-top-left-radius: 10px;
		border-top-right-radius: 10px;
		height: 20rem;
	}

	.movie_info {
		color: #5e5c5c;
	}

	.movie_info i {
		font-size: 20px;
	}

	.card-title {
		width: 80%;
		height: 4rem;
	}

	.play_button {
		background-color: #ff3d49;
		position: absolute;
		width: 60px;
		height: 60px;
		border-radius: 50%;
		right: 20px;
		bottom: 111px;
		font-size: 27px;
		padding-left: 21px;
		padding-top: 16px;
		color: #FFFFFF;
		cursor: pointer;
	}
</style>

<div class="d-flex justify-content-center flex-wrap">
    {% for movie in movies %}
        <form id="movie_add_form" method="post" action="{% url "movie:add_movie" %}">
    {% csrf_token %}
    <input type="text" hidden name="title" value="{{ movie.title }}">
    <input type="text" hidden name="img_url" value="{{ movie.poster }}">
    <input type="text" hidden name="year" value="{{ movie.year }}">
    <input type="text" hidden name="rating" value="{{ movie.rating }}">
    <input type="text" hidden name="path" value="{{ request.path|urlencode }}">
	<div class="card movie_card center">
		<img src="{{ movie.poster }}" class="card-img-top" alt="...">
		<div class="card-body">
			<i class="fas fa-play play_button" data-toggle="modal" data-target=".bd-example-modal-xl"
				data-placement="bottom" title="Play Trailer">
			</i>
			<h5 class="card-title">{{ movie.title|truncatechars:30 }}</h5>
			<span class="movie_info">{{ movie.release_date }}</span>
			<span class="movie_info float-right">
                <a title="Add to wishlist" href="#"
                   onclick="document.getElementById('movie_add_form').submit()">
                    <i class="fas fa-plus"></i> </a>
                <i class="fas fa-star"></i> {{ movie.rating }} / 10</span>
		</div>
	</div>
        </form>
{% endfor %}
    </div>
    <br><p align="center"><a href="" class="btn btn-primary">Next</a></p><br>
{% endblock %}

{% block content %}

{% endblock %}

templates/movie/edit_movie.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit item{% endblock %}


{% block nav %}
<link rel="stylesheet" href="{% static 'stylesheets/library/custom_style.css' %}">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Edit item</h1>
{#    <p class="lead">{{ quote }}</p>#}
  </div>
</div>
{% endblock %}

{% block content %}

<div class="form-group">
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{#<a class="btn btn-danger" href="{% url "movie:delete_item" id %}">Delete</a>#}
</div>


{% endblock %}

templates/movie/watch_now.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Movie Recommender{% endblock %}

{% block nav %}
<link rel="stylesheet" href="{% static 'stylesheets/library/custom_style.css' %}">
<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1 class="display-4">Watch Now</h1>
		<p class="lead">{{ quote }}</p>
	</div>
</div>

{% endblock %}

{% block content %}
{#<form action="{% url 'movie:custom-filter' %}" method="POST">#}
{#	{% csrf_token %}#}
{#	<div class="row">#}
{#		<div class="col">#}
{#			Release year#}
{#			<div class="row">#}
{#				<div class="col">#}
{#					<input type="text" name="from-year" class="form-control form-control-sm" placeholder="From e.g 1996">#}
{#				</div>#}
{#				<div class="col"><input name="to-year" type="text" class="form-control form-control-sm" placeholder="To e.g 2018">#}
{#				</div>#}
{#			</div>#}
{#		</div>#}

{#		<div class="col">#}
{#			Genre#}
{#			<select class="form-control form-control-sm" name="genre">#}
{#				<option value="" disabled selected>Genre</option>#}
{#				<option value="sci_fi" >Sci-Fi</option>#}
{#				<option value="thriller" >Thriller</option>#}
{#				<option value="action">Action</option>#}
{#				<option value="adventure">Adventure</option>#}
{#				<option value="animation" >Animation</option>#}
{#				<option value="biography" >Biography</option>#}
{#				<option value="comedy" >Comedy</option>#}
{#				<option value="crime" >Crime</option>#}
{#				<option value="documentary" >Documentary</option>#}
{#				<option value="drama" >Drama</option>#}
{#				<option value="fantasy" >Fantasy</option>#}
{#				<option value="history" >History</option>#}
{#				<option value="horror" >Horror</option>#}
{#				<option value="mystery" >Mystery</option>#}
{##}
{#			</select>#}
{#		</div>#}
{#		<div class="col">#}
{#			Rating#}
{#			<div class="row">#}
{#				<div class="col">#}
{#					<input type="text" name="from-rating" class="form-control form-control-sm" placeholder="From rating e.g. 7">#}
{#				</div>#}
{#				<div class="col">#}
{#					<input name="to-rating" type="text" class="form-control form-control-sm" placeholder="To rating e.g. 9">#}
{#				</div>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
{#	<br><p align="center"><button style="background-color: #ea3a60; color: whitesmoke; border-radius: 4px;#}
{#	 border-color: #ea3a60;" type="submit">Suggest movie</button></p><br>#}
{#</form>#}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
	integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<style>
	img {
		-webkit-user-drag: none;
		-moz-user-drag: none;
		-o-user-drag: none;
		user-drag: none;
	}

	img {
		pointer-events: none;
	}

	.movie_card {
		padding: 0 !important;
		width: 15rem;
		margin: 14px;
		border-radius: 10px;
		box-shadow: 0 3px 4px 0 rgba(0, 0, 0, 0.2), 0 4px 15px 0 rgba(0, 0, 0, 0.19);
	}

	.movie_card img {
		border-top-left-radius: 10px;
		border-top-right-radius: 10px;
		height: 20rem;
	}

	.movie_info {
		color: #5e5c5c;
	}

	.movie_info i {
		font-size: 20px;
	}

	.card-title {
		width: 80%;
		height: 4rem;
	}

	.play_button {
		background-color: #ff3d49;
		position: absolute;
		width: 60px;
		height: 60px;
		border-radius: 50%;
		right: 20px;
		bottom: 111px;
		font-size: 27px;
		padding-left: 21px;
		padding-top: 16px;
		color: #FFFFFF;
		cursor: pointer;
	}
</style>




<div class="container d-flex justify-content-center">
<form id="movie_add_form" method="post" action="{% url "movie:add_movie" %}">
    {% csrf_token %}
    <input type="text" hidden name="title" value="{{ movie.title }}">
    <input type="text" hidden name="img_url" value="{{ movie.poster }}">
    <input type="text" hidden name="year" value="{{ movie.year }}">
    <input type="text" hidden name="rating" value="{{ movie.rating }}">
    <input type="text" hidden name="path" value="{{ request.path|urlencode }}">
	<div class="card movie_card center">
		<img src="{{ movie.poster }}" class="card-img-top" alt="...">
		<div class="card-body">
			<i class="fas fa-play play_button" data-toggle="modal" data-target=".bd-example-modal-xl"
				data-placement="bottom" title="Play Trailer">
			</i>
			<h5 class="card-title">{{ movie.title|truncatechars:30 }}</h5>
			<span class="movie_info">{{ movie.release_date }}</span>
			<span class="movie_info float-right">
                {% if request.user.is_authenticated %}
                <a title="Add to wishlist" href="#"
                   onclick="document.getElementById('movie_add_form').submit()">
                    <i class="fas fa-plus"></i> </a>
                {% endif %}
                <i class="fas fa-star"></i> {{ movie.rating }} / 10</span>
		</div>
	</div>
</form>
</div>
<p align="center"><a href="" class="btn btn-primary">Next</a></p><br>

<!-- Extra large modal -->
<div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel"
	aria-hidden="true">
	<div class="modal-dialog modal-xl" role="document">
		<div class="modal-content">
			<iframe width="100%" height="720" src="https://www.youtube.com/embed/{{ movie.trailer }}" frameborder="0"
				allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
				allowfullscreen></iframe>

		</div>
	</div>
</div>


{% endblock %}