movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.watch_now, name='watch_now'),
    path('library/', views.movie_library, name='movie_library'),
    path('custom-filter/', views.custom_filter, name='custom-filter'),
    path('add-item/', views.add_item, name='add_movie'),
    path('edit_movie/<int:id>', views.edit_item, name='edit_movie'),
    path('delete_item/<int:id>', views.delete_item, name='delete_item'),

]

movie_recommender/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls', namespace='movie')),
    path('account/', include('account.urls', namespace='account')),
    path('account/', include('django.contrib.auth.urls')),

]

movie/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Movie(models.Model):
    STATUS_CHOICES = (
        ('Movie', 'Movie'),
        ('Tv-series', 'Tv Series'),
        ('Anime', 'Anime'),
    )
    WATCH_CHOICES = (
        ('Watched', 'Watched'),
        ('To watch', 'To watch'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=False)
    type = models.CharField(max_length=15,
                            choices=STATUS_CHOICES,
                            default='')
    watch = models.CharField(max_length=20,
                             choices=WATCH_CHOICES)
    year = models.IntegerField(null=True, blank=True)
    rating = models.FloatField(max_length=10, null=False)
    review = models.TextField(null=True, blank=True)
    img_url = models.TextField(default='https://betravingknows.com/wp-content/uploads/2017/'
                                       '06/video-movie-placeholder-image-grey.png')
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

movie/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'review',
                  'rating', 'img_url',
                  'watch', 'type',
                  'active')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'review': forms.TextInput(attrs={'class': 'form-control'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                              'style': 'margin-bottom: 10px;'}),
            'rating': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'img_url', 'watch', 'active')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                              'style': 'margin-bottom: 10px;'}),
            'rating': forms.TextInput(attrs={'class': 'form-control'}),
        }

movie/views.py
from django.shortcuts import render, redirect
from .movie_recommender import movie_list_creator, trailer_finder, poster_finder, movie_list, randomizer
from .movie_dialoge_generater import quotes
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import MovieForm, EditForm
import random
from .models import Movie
from django.contrib.auth.decorators import login_required


def watch_now(request):
    quote = random.choice(quotes)
    random_movie = random.choice(movie_list)
    random_movie['poster'] = poster_finder(random_movie)
    random_movie['trailer'] = trailer_finder(random_movie)
    return render(request, 'movie/watch_now.html', {
        'movie': random_movie,
        'quote': quote,
    })


def custom_filter(request):
    quote = random.choice(quotes)
    if request.method == "POST":
        if 'movies' in request.session:
            del request.session['movies']
        request.session['from_year'] = request.POST['from-year']
        request.session['to_year'] = request.POST['to-year']
        try:
            request.session['genre'] = request.POST['genre']
        except:
            request.session['genre'] = ''
        request.session['from_rating'] = request.POST['from-rating']
        request.session['to_rating'] = request.POST['to-rating']
        custom_movie_list = movie_list_creator(request.session['from_year'],
                                               request.session['to_year'],
                                               request.session['genre'],
                                               request.session['from_rating'],
                                               request.session['to_rating'],
                                               )
        request.session['movies'] = custom_movie_list
    try:
        x_movie_list = request.session['movies']
    except KeyError:
        x_movie_list = movie_list
    try:
        start, end = randomizer(request.session['movies'])
    except KeyError:
        start, end = randomizer(movie_list)
    new_list = []
    for movie in x_movie_list[start:end]:
        movie['poster'] = poster_finder(movie)
        movie['trailer'] = trailer_finder(movie)
        new_list.append(movie)
    return render(request, 'movie/custom-filter.html', {'movies': new_list,
                                                        'quote': quote,
                                                        })


@login_required
def add_item(request):  # add new media
    quote = random.choice(quotes)
    user = request.user
    if request.method == "POST":
        path = request.POST.get('path')
        if not path:
            # if the add request is from add item page.
            form = MovieForm(request.POST)
            if form.is_valid():
                new_item = form.save(commit=False)
                new_item.author = user
                new_item.save()
                return redirect('movie:movie_library')
        else:
            # if the request is direct from the watch now or custom filter page.
            title = request.POST['title']
            image_url = request.POST['img_url']
            # year = request.POST['year']
            rating = request.POST['rating']
            new_item = Movie(title=title, img_url=image_url,
                             rating=rating, author=user,
                             watch="To watch")
            new_item.save()
            return redirect(path)
    return render(request, 'movie/add_movie.html',
                  context={'form': MovieForm(),
                           'quote': quote})


@login_required
def movie_library(request):  # movie library
    user = request.user
    quote = random.choice(quotes)
    movies = Movie.objects.filter(author=user, active=True)
    # paginator = Paginator(movies, 12)
    # page = request.GET.get('page')
    # try:
    #     movies = paginator.page(page)
    # except PageNotAnInteger:
    #     movies = paginator.page(1)
    # except EmptyPage:
    #     movies = paginator.page(paginator.num_pages)
    return render(request, 'movie/library/list.html', {'movies': movies,
                                                       'quote': quote,
                                                       # 'page': page,
                                                       'total': len(movies),
                                                       })


@login_required
def edit_item(request, id):
    movie = Movie.objects.get(pk=id)
    data = {'title': movie.title,
            'img_url': movie.img_url,
            'watch': movie.watch,
            'active': movie.active}
    form = EditForm(initial=data)
    if request.user == movie.author:
        if request.method == "POST":
            form = EditForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                movie.title = cd['title']
                movie.img_url = cd['img_url']
                movie.watch = cd['watch']
                movie.active = cd['active']
                movie.save()
                return redirect('movie:movie_library')
    return render(request, 'movie/edit_movie.html',
                  {'form': form,
                   'id': movie.id})


@login_required
def delete_item(request, id):
    movie = Movie.objects.get(pk=id)
    if request.user == movie.author:
        movie.delete()
        return redirect('movie:movie_library')

templates/movie/library/list.html
{% extends 'base.html' %}
{% block title %}Wish list{% endblock %}
{% load static %}


{% block nav %}
<link rel="stylesheet" href="{% static 'stylesheets/library/custom_style.css' %}">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Wish list</h1>
    <p class="lead">{{ quote }}</p>
  </div>
</div>
{% endblock %}

{% block content %}


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
	integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<style>
	img {
		-webkit-user-drag: none;
		-moz-user-drag: none;
		-o-user-drag: none;
		user-drag: none;
	}

	img {
		pointer-events: none;
	}

	.movie_card {
		padding: 0 !important;
		width: 15rem;
		margin: 14px;
		border-radius: 10px;
		box-shadow: 0 3px 4px 0 rgba(0, 0, 0, 0.2), 0 4px 15px 0 rgba(0, 0, 0, 0.19);
	}

	.movie_card img {
		border-top-left-radius: 10px;
		border-top-right-radius: 10px;
		height: 20rem;
	}

	.movie_info {
		color: #5e5c5c;
	}

	.movie_info i {
		font-size: 20px;
	}

	.card-title {
		width: 80%;
		height: 4rem;
	}

	.play_button {
		background-color: #ff3d49;
		position: absolute;
		width: 60px;
		height: 60px;
		border-radius: 50%;
		right: 20px;
		bottom: 111px;
		font-size: 27px;
		padding-left: 21px;
		padding-top: 16px;
		color: #FFFFFF;
		cursor: pointer;
	}
</style>

<div class="container d-flex flex-wrap">
	{% for movie in movies %}

	<div class="card movie_card">
		<img src="{{ movie.img_url }}" class="card-img-top" alt="...">
		<div class="card-body">
         <a href="{% url "movie:edit_movie" id=movie.id %}">
             <i style="float: right" class="far fa-edit"></i>
         </a>
            <a href="{% url "movie:delete_item" id=movie.id %}">
             <i style="float: right" class="fas fa-trash"></i>
         </a>
			<h5 class="card-title">{{ movie.title|truncatechars:30 }}</h5>
			<span class="movie_info">{{ movie.type }}</span>
			<span class="movie_info float-right">
                {% if movie.watch == "To watch" %}
                <i title="To watch" class="fas fa-spinner"></i>
                {% endif %}
                <i class="fas fa-star"></i> {{ movie.rating }}</span>
		</div>
	</div>

	{% endfor %}
</div>
     <div class="container text-center m-5">
<a class="btn btn-primary" href="{% url "movie:add_movie" %}" class="button">Add New</a>
</div>
{% endblock %}